name: betto_charset_detector
description: >-
  A pure-Dart charset detection library for Dart and Flutter applications.

version: 0.1.0-dev.2
repository: https://github.com/bettongia/charset_detector
issue_tracker: https://github.com/bettongia/charset_detector/issues
homepage: https://bettongia.github.io/charset_detector/

topics:
  - charset

environment:
  sdk: ^3.12.0

# Add regular dependencies here.
dependencies:
  charset: ^2.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
